
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package edEXT.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-21T01:20:03.085-03:00
 * Generated source version: 3.4.0
 *
 */

@javax.jws.WebService(
                      serviceName = "ServidorService",
                      portName = "ServidorPort",
                      targetNamespace = "http://server.edEXT/",
                      wsdlLocation = "http://localhost:9122/edEXTServidor?wsdl",
                      endpointInterface = "edEXT.server.Servidor")

public class ServidorPortImpl implements Servidor {

    private static final Logger LOG = Logger.getLogger(ServidorPortImpl.class.getName());

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarProgramasFormacionString()*
     */
    public edEXT.server.DtListaString listarProgramasFormacionString() {
        LOG.info("Executing operation listarProgramasFormacionString");
        try {
            edEXT.server.DtListaString _return = new edEXT.server.DtListaString();
            java.util.List<java.lang.String> _returnLista = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnListaVal1 = "_returnListaVal1859860950";
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#altaInstituto(java.lang.String arg0)*
     */
    public java.lang.String altaInstituto(java.lang.String arg0) {
        LOG.info("Executing operation altaInstituto");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1533266354";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#incrementarVisitaCurso(java.lang.String arg0)*
     */
    public java.lang.Integer incrementarVisitaCurso(java.lang.String arg0) {
        LOG.info("Executing operation incrementarVisitaCurso");
        System.out.println(arg0);
        try {
            java.lang.Integer _return = Integer.valueOf(-996030711);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#seleccionarUsuario(java.lang.String arg0)*
     */
    public edEXT.server.DtInfoUsuario seleccionarUsuario(java.lang.String arg0) {
        LOG.info("Executing operation seleccionarUsuario");
        System.out.println(arg0);
        try {
            edEXT.server.DtInfoUsuario _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarCursosCategoriaString(java.lang.String arg0)*
     */
    public edEXT.server.DtListaString listarCursosCategoriaString(java.lang.String arg0) {
        LOG.info("Executing operation listarCursosCategoriaString");
        System.out.println(arg0);
        try {
            edEXT.server.DtListaString _return = new edEXT.server.DtListaString();
            java.util.List<java.lang.String> _returnLista = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnListaVal1 = "_returnListaVal468812522";
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#puntuarCurso(java.lang.String arg0, java.lang.String arg1, java.lang.Integer arg2)*
     */
    public java.lang.String puntuarCurso(java.lang.String arg0, java.lang.String arg1, java.lang.Integer arg2) {
        LOG.info("Executing operation puntuarCurso");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "_return1332763787";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#getDtInfoCursoEdicion(java.lang.String arg0)*
     */
    public edEXT.server.DtCursoEdicion getDtInfoCursoEdicion(java.lang.String arg0) {
        LOG.info("Executing operation getDtInfoCursoEdicion");
        System.out.println(arg0);
        try {
            edEXT.server.DtCursoEdicion _return = new edEXT.server.DtCursoEdicion();
            _return.setNombre("Nombre-1014444548");
            _return.setInstituto("Instituto106158703");
            _return.setCurso("Curso-1315547257");
            _return.setFechaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.132-03:00"));
            _return.setFechaFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.133-03:00"));
            _return.setCupo(-955190883);
            _return.setFechaRegistro(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.134-03:00"));
            _return.setUrlImagen("UrlImagen-575823333");
            _return.setVigente(false);
            _return.setFinalizada(false);
            java.util.List<java.lang.String> _returnDictadoPor = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnDictadoPorVal1 = "_returnDictadoPorVal-1765318035";
            _returnDictadoPor.add(_returnDictadoPorVal1);
            _return.getDictadoPor().addAll(_returnDictadoPor);
            java.util.List<edEXT.server.DtInfoDocente> _returnDocentes = new java.util.ArrayList<edEXT.server.DtInfoDocente>();
            edEXT.server.DtInfoDocente _returnDocentesVal1 = new edEXT.server.DtInfoDocente();
            _returnDocentesVal1.setApellido("Apellido1649619189");
            _returnDocentesVal1.setClave("Clave-1120241253");
            _returnDocentesVal1.setCorreoElectronico("CorreoElectronico2144428933");
            _returnDocentesVal1.setFechaNacimiento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.135-03:00"));
            _returnDocentesVal1.setNickname("Nickname1897744165");
            _returnDocentesVal1.setNombre("Nombre-536097383");
            _returnDocentesVal1.setTipo("Tipo-696383307");
            _returnDocentesVal1.setUrlFoto("UrlFoto1229192816");
            _returnDocentesVal1.setInstituto("Instituto613786361");
            java.util.List<edEXT.server.DtInfoCurso> _returnDocentesVal1Cursos = new java.util.ArrayList<edEXT.server.DtInfoCurso>();
            _returnDocentesVal1.getCursos().addAll(_returnDocentesVal1Cursos);
            java.util.List<edEXT.server.DtCursoEdicion> _returnDocentesVal1Ediciones = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            _returnDocentesVal1.getEdiciones().addAll(_returnDocentesVal1Ediciones);
            java.util.List<edEXT.server.DtProgramaFormacion> _returnDocentesVal1Programas = new java.util.ArrayList<edEXT.server.DtProgramaFormacion>();
            _returnDocentesVal1.getProgramas().addAll(_returnDocentesVal1Programas);
            _returnDocentes.add(_returnDocentesVal1);
            _return.getDocentes().addAll(_returnDocentes);
            java.util.List<edEXT.server.DtInscripcionEdicion> _returnInscripciones = new java.util.ArrayList<edEXT.server.DtInscripcionEdicion>();
            edEXT.server.DtInscripcionEdicion _returnInscripcionesVal1 = new edEXT.server.DtInscripcionEdicion();
            _returnInscripcionesVal1.setEdicion("Edicion1939103949");
            _returnInscripcionesVal1.setCurso("Curso1747134629");
            edEXT.server.DtInfoEstudiante _returnInscripcionesVal1Estudiante = new edEXT.server.DtInfoEstudiante();
            _returnInscripcionesVal1Estudiante.setApellido("Apellido-2017455434");
            _returnInscripcionesVal1Estudiante.setClave("Clave-1042800464");
            _returnInscripcionesVal1Estudiante.setCorreoElectronico("CorreoElectronico575391042");
            _returnInscripcionesVal1Estudiante.setFechaNacimiento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.138-03:00"));
            _returnInscripcionesVal1Estudiante.setNickname("Nickname1048320918");
            _returnInscripcionesVal1Estudiante.setNombre("Nombre1052491533");
            _returnInscripcionesVal1Estudiante.setTipo("Tipo-223014046");
            _returnInscripcionesVal1Estudiante.setUrlFoto("UrlFoto742863625");
            java.util.List<edEXT.server.DtInscripcionEdicion> _returnInscripcionesVal1EstudianteInscripEdiciones = new java.util.ArrayList<edEXT.server.DtInscripcionEdicion>();
            _returnInscripcionesVal1Estudiante.getInscripEdiciones().addAll(_returnInscripcionesVal1EstudianteInscripEdiciones);
            java.util.List<edEXT.server.DtInscripcionPrograma> _returnInscripcionesVal1EstudianteInscripProgramas = new java.util.ArrayList<edEXT.server.DtInscripcionPrograma>();
            _returnInscripcionesVal1Estudiante.getInscripProgramas().addAll(_returnInscripcionesVal1EstudianteInscripProgramas);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnInscripcionesVal1EstudiantePuntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnInscripcionesVal1Estudiante.getPuntajes().addAll(_returnInscripcionesVal1EstudiantePuntajes);
            _returnInscripcionesVal1.setEstudiante(_returnInscripcionesVal1Estudiante);
            _returnInscripcionesVal1.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.139-03:00"));
            _returnInscripcionesVal1.setEstado("Estado-357336893");
            _returnInscripcionesVal1.setUrlVideo("UrlVideo-1562958145");
            _returnInscripcionesVal1.setNota(Integer.valueOf(2070036355));
            _returnInscripcionesVal1.setFechaNota(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.140-03:00"));
            _returnInscripciones.add(_returnInscripcionesVal1);
            _return.getInscripciones().addAll(_returnInscripciones);
            java.util.List<edEXT.server.DtCursoEdicionComentario> _returnComentarios = new java.util.ArrayList<edEXT.server.DtCursoEdicionComentario>();
            edEXT.server.DtCursoEdicionComentario _returnComentariosVal1 = new edEXT.server.DtCursoEdicionComentario();
            _returnComentariosVal1.setId(8610159306678257430l);
            _returnComentariosVal1.setEdicion("Edicion-773480074");
            _returnComentariosVal1.setEstudiante("Estudiante-959664097");
            _returnComentariosVal1.setTexto("Texto1726590242");
            _returnComentariosVal1.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.141-03:00"));
            _returnComentariosVal1.setIdPadre(5436300026311185498l);
            java.util.List<edEXT.server.DtCursoEdicionComentario> _returnComentariosVal1Respuestas = new java.util.ArrayList<edEXT.server.DtCursoEdicionComentario>();
            _returnComentariosVal1.getRespuestas().addAll(_returnComentariosVal1Respuestas);
            _returnComentarios.add(_returnComentariosVal1);
            _return.getComentarios().addAll(_returnComentarios);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#agregarPreviaCurso(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String agregarPreviaCurso(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation agregarPreviaCurso");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-639886233";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarCategorias()*
     */
    public edEXT.server.DtListaString listarCategorias() {
        LOG.info("Executing operation listarCategorias");
        try {
            edEXT.server.DtListaString _return = new edEXT.server.DtListaString();
            java.util.List<java.lang.String> _returnLista = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnListaVal1 = "_returnListaVal153250053";
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarUsuarios()*
     */
    public edEXT.server.DtListaUsuarios listarUsuarios() {
        LOG.info("Executing operation listarUsuarios");
        try {
            edEXT.server.DtListaUsuarios _return = new edEXT.server.DtListaUsuarios();
            java.util.List<edEXT.server.DtInfoUsuario> _returnLista = new java.util.ArrayList<edEXT.server.DtInfoUsuario>();
            edEXT.server.DtInfoUsuario _returnListaVal1 = null;
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#finalizarEdicion(java.lang.String arg0)*
     */
    public java.lang.String finalizarEdicion(java.lang.String arg0) {
        LOG.info("Executing operation finalizarEdicion");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1052937997";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#seleccionarUsuarioCorreo(java.lang.String arg0)*
     */
    public edEXT.server.DtInfoUsuario seleccionarUsuarioCorreo(java.lang.String arg0) {
        LOG.info("Executing operation seleccionarUsuarioCorreo");
        System.out.println(arg0);
        try {
            edEXT.server.DtInfoUsuario _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#altaEstudiante(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, javax.xml.datatype.XMLGregorianCalendar arg4, java.lang.String arg5, java.lang.String arg6)*
     */
    public java.lang.String altaEstudiante(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, javax.xml.datatype.XMLGregorianCalendar arg4, java.lang.String arg5, java.lang.String arg6) {
        LOG.info("Executing operation altaEstudiante");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        try {
            java.lang.String _return = "_return-1767094179";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarEstudiantes()*
     */
    public edEXT.server.DtListaString listarEstudiantes() {
        LOG.info("Executing operation listarEstudiantes");
        try {
            edEXT.server.DtListaString _return = new edEXT.server.DtListaString();
            java.util.List<java.lang.String> _returnLista = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnListaVal1 = "_returnListaVal1279828331";
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarCursos()*
     */
    public edEXT.server.DtListaCursos listarCursos() {
        LOG.info("Executing operation listarCursos");
        try {
            edEXT.server.DtListaCursos _return = new edEXT.server.DtListaCursos();
            java.util.List<edEXT.server.DtInfoCurso> _returnLista = new java.util.ArrayList<edEXT.server.DtInfoCurso>();
            edEXT.server.DtInfoCurso _returnListaVal1 = new edEXT.server.DtInfoCurso();
            _returnListaVal1.setNombre("Nombre1223659269");
            _returnListaVal1.setInstituto("Instituto-1141348332");
            _returnListaVal1.setDescripcion("Descripcion-2070130219");
            _returnListaVal1.setDuracion("Duracion678155304");
            _returnListaVal1.setCantidadHoras(590267288);
            _returnListaVal1.setCreditos(-685511537);
            _returnListaVal1.setUrl("Url1840405834");
            _returnListaVal1.setFechaAlta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.150-03:00"));
            _returnListaVal1.setUrlImagen("UrlImagen1384280005");
            _returnListaVal1.setVisitas(Integer.valueOf(1057729937));
            _returnListaVal1.setPuntaje(Float.valueOf(0.34963667f));
            java.util.List<java.lang.String> _returnListaVal1Previas = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getPrevias().addAll(_returnListaVal1Previas);
            java.util.List<edEXT.server.DtCursoEdicion> _returnListaVal1Ediciones = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            _returnListaVal1.getEdiciones().addAll(_returnListaVal1Ediciones);
            java.util.List<edEXT.server.DtProgramaFormacion> _returnListaVal1Programas = new java.util.ArrayList<edEXT.server.DtProgramaFormacion>();
            _returnListaVal1.getProgramas().addAll(_returnListaVal1Programas);
            java.util.List<java.lang.String> _returnListaVal1Categorias = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getCategorias().addAll(_returnListaVal1Categorias);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnListaVal1Puntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnListaVal1.getPuntajes().addAll(_returnListaVal1Puntajes);
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarInstitutos()*
     */
    public edEXT.server.DtListaString listarInstitutos() {
        LOG.info("Executing operation listarInstitutos");
        try {
            edEXT.server.DtListaString _return = new edEXT.server.DtListaString();
            java.util.List<java.lang.String> _returnLista = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnListaVal1 = "_returnListaVal-588941935";
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#aceptarInscripcionEdicion(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String aceptarInscripcionEdicion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation aceptarInscripcionEdicion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return1399071769";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarCursosInstituto(java.lang.String arg0)*
     */
    public edEXT.server.DtListaCursos listarCursosInstituto(java.lang.String arg0) {
        LOG.info("Executing operation listarCursosInstituto");
        System.out.println(arg0);
        try {
            edEXT.server.DtListaCursos _return = new edEXT.server.DtListaCursos();
            java.util.List<edEXT.server.DtInfoCurso> _returnLista = new java.util.ArrayList<edEXT.server.DtInfoCurso>();
            edEXT.server.DtInfoCurso _returnListaVal1 = new edEXT.server.DtInfoCurso();
            _returnListaVal1.setNombre("Nombre998079561");
            _returnListaVal1.setInstituto("Instituto-905376911");
            _returnListaVal1.setDescripcion("Descripcion271914777");
            _returnListaVal1.setDuracion("Duracion-552908688");
            _returnListaVal1.setCantidadHoras(-1504043748);
            _returnListaVal1.setCreditos(1141503006);
            _returnListaVal1.setUrl("Url-1423924092");
            _returnListaVal1.setFechaAlta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.153-03:00"));
            _returnListaVal1.setUrlImagen("UrlImagen-190941553");
            _returnListaVal1.setVisitas(Integer.valueOf(-1587358697));
            _returnListaVal1.setPuntaje(Float.valueOf(0.9245108f));
            java.util.List<java.lang.String> _returnListaVal1Previas = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getPrevias().addAll(_returnListaVal1Previas);
            java.util.List<edEXT.server.DtCursoEdicion> _returnListaVal1Ediciones = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            _returnListaVal1.getEdiciones().addAll(_returnListaVal1Ediciones);
            java.util.List<edEXT.server.DtProgramaFormacion> _returnListaVal1Programas = new java.util.ArrayList<edEXT.server.DtProgramaFormacion>();
            _returnListaVal1.getProgramas().addAll(_returnListaVal1Programas);
            java.util.List<java.lang.String> _returnListaVal1Categorias = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getCategorias().addAll(_returnListaVal1Categorias);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnListaVal1Puntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnListaVal1.getPuntajes().addAll(_returnListaVal1Puntajes);
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#crearEdicionCurso(java.lang.String arg0, java.lang.String arg1, javax.xml.datatype.XMLGregorianCalendar arg2, javax.xml.datatype.XMLGregorianCalendar arg3, int arg4, javax.xml.datatype.XMLGregorianCalendar arg5, java.lang.String arg6, java.util.List<java.lang.String> arg7)*
     */
    public java.lang.String crearEdicionCurso(java.lang.String arg0, java.lang.String arg1, javax.xml.datatype.XMLGregorianCalendar arg2, javax.xml.datatype.XMLGregorianCalendar arg3, int arg4, javax.xml.datatype.XMLGregorianCalendar arg5, java.lang.String arg6, java.util.List<java.lang.String> arg7) {
        LOG.info("Executing operation crearEdicionCurso");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        try {
            java.lang.String _return = "_return-1169616775";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#seleccionarCurso(java.lang.String arg0)*
     */
    public edEXT.server.DtListaCursoEdiciones seleccionarCurso(java.lang.String arg0) {
        LOG.info("Executing operation seleccionarCurso");
        System.out.println(arg0);
        try {
            edEXT.server.DtListaCursoEdiciones _return = new edEXT.server.DtListaCursoEdiciones();
            java.util.List<edEXT.server.DtCursoEdicion> _returnLista = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            edEXT.server.DtCursoEdicion _returnListaVal1 = new edEXT.server.DtCursoEdicion();
            _returnListaVal1.setNombre("Nombre273306100");
            _returnListaVal1.setInstituto("Instituto1874144239");
            _returnListaVal1.setCurso("Curso1888287388");
            _returnListaVal1.setFechaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.161-03:00"));
            _returnListaVal1.setFechaFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.162-03:00"));
            _returnListaVal1.setCupo(-1415393097);
            _returnListaVal1.setFechaRegistro(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.162-03:00"));
            _returnListaVal1.setUrlImagen("UrlImagen660209505");
            _returnListaVal1.setVigente(false);
            _returnListaVal1.setFinalizada(true);
            java.util.List<java.lang.String> _returnListaVal1DictadoPor = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getDictadoPor().addAll(_returnListaVal1DictadoPor);
            java.util.List<edEXT.server.DtInfoDocente> _returnListaVal1Docentes = new java.util.ArrayList<edEXT.server.DtInfoDocente>();
            _returnListaVal1.getDocentes().addAll(_returnListaVal1Docentes);
            java.util.List<edEXT.server.DtInscripcionEdicion> _returnListaVal1Inscripciones = new java.util.ArrayList<edEXT.server.DtInscripcionEdicion>();
            _returnListaVal1.getInscripciones().addAll(_returnListaVal1Inscripciones);
            java.util.List<edEXT.server.DtCursoEdicionComentario> _returnListaVal1Comentarios = new java.util.ArrayList<edEXT.server.DtCursoEdicionComentario>();
            _returnListaVal1.getComentarios().addAll(_returnListaVal1Comentarios);
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#seleccionarProgramaFormacion(java.lang.String arg0)*
     */
    public edEXT.server.DtProgramaFormacion seleccionarProgramaFormacion(java.lang.String arg0) {
        LOG.info("Executing operation seleccionarProgramaFormacion");
        System.out.println(arg0);
        try {
            edEXT.server.DtProgramaFormacion _return = new edEXT.server.DtProgramaFormacion();
            _return.setNombre("Nombre1718316654");
            _return.setDescripcion("Descripcion1625362587");
            _return.setFechaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.164-03:00"));
            _return.setFechaFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.165-03:00"));
            _return.setUrlImagen("UrlImagen-1447088955");
            java.util.List<java.lang.String> _returnCursos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCursosVal1 = "_returnCursosVal-383709260";
            _returnCursos.add(_returnCursosVal1);
            _return.getCursos().addAll(_returnCursos);
            java.util.List<java.lang.String> _returnCategorias = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCategoriasVal1 = "_returnCategoriasVal-579385399";
            _returnCategorias.add(_returnCategoriasVal1);
            _return.getCategorias().addAll(_returnCategorias);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#obtenerCertificadoProgramaFormacion(java.lang.String arg0, java.lang.String arg1)*
     */
    public edEXT.server.DtCertificadoProgramaFormacion obtenerCertificadoProgramaFormacion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation obtenerCertificadoProgramaFormacion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            edEXT.server.DtCertificadoProgramaFormacion _return = new edEXT.server.DtCertificadoProgramaFormacion();
            edEXT.server.DtInfoEstudiante _returnEstudiante = new edEXT.server.DtInfoEstudiante();
            _returnEstudiante.setApellido("Apellido154265711");
            _returnEstudiante.setClave("Clave-1687203450");
            _returnEstudiante.setCorreoElectronico("CorreoElectronico1702816140");
            _returnEstudiante.setFechaNacimiento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.168-03:00"));
            _returnEstudiante.setNickname("Nickname-1298049329");
            _returnEstudiante.setNombre("Nombre-1199056139");
            _returnEstudiante.setTipo("Tipo627773776");
            _returnEstudiante.setUrlFoto("UrlFoto66014042");
            java.util.List<edEXT.server.DtInscripcionEdicion> _returnEstudianteInscripEdiciones = new java.util.ArrayList<edEXT.server.DtInscripcionEdicion>();
            edEXT.server.DtInscripcionEdicion _returnEstudianteInscripEdicionesVal1 = new edEXT.server.DtInscripcionEdicion();
            _returnEstudianteInscripEdicionesVal1.setEdicion("Edicion1148195179");
            _returnEstudianteInscripEdicionesVal1.setCurso("Curso771526168");
            edEXT.server.DtInfoEstudiante _returnEstudianteInscripEdicionesVal1Estudiante = new edEXT.server.DtInfoEstudiante();
            _returnEstudianteInscripEdicionesVal1Estudiante.setApellido("Apellido-1200911063");
            _returnEstudianteInscripEdicionesVal1Estudiante.setClave("Clave248766735");
            _returnEstudianteInscripEdicionesVal1Estudiante.setCorreoElectronico("CorreoElectronico-1801472312");
            _returnEstudianteInscripEdicionesVal1Estudiante.setFechaNacimiento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.169-03:00"));
            _returnEstudianteInscripEdicionesVal1Estudiante.setNickname("Nickname-615227819");
            _returnEstudianteInscripEdicionesVal1Estudiante.setNombre("Nombre1477301428");
            _returnEstudianteInscripEdicionesVal1Estudiante.setTipo("Tipo2018313190");
            _returnEstudianteInscripEdicionesVal1Estudiante.setUrlFoto("UrlFoto1081318882");
            java.util.List<edEXT.server.DtInscripcionEdicion> _returnEstudianteInscripEdicionesVal1EstudianteInscripEdiciones = new java.util.ArrayList<edEXT.server.DtInscripcionEdicion>();
            _returnEstudianteInscripEdicionesVal1Estudiante.getInscripEdiciones().addAll(_returnEstudianteInscripEdicionesVal1EstudianteInscripEdiciones);
            java.util.List<edEXT.server.DtInscripcionPrograma> _returnEstudianteInscripEdicionesVal1EstudianteInscripProgramas = new java.util.ArrayList<edEXT.server.DtInscripcionPrograma>();
            _returnEstudianteInscripEdicionesVal1Estudiante.getInscripProgramas().addAll(_returnEstudianteInscripEdicionesVal1EstudianteInscripProgramas);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnEstudianteInscripEdicionesVal1EstudiantePuntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnEstudianteInscripEdicionesVal1Estudiante.getPuntajes().addAll(_returnEstudianteInscripEdicionesVal1EstudiantePuntajes);
            _returnEstudianteInscripEdicionesVal1.setEstudiante(_returnEstudianteInscripEdicionesVal1Estudiante);
            _returnEstudianteInscripEdicionesVal1.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.172-03:00"));
            _returnEstudianteInscripEdicionesVal1.setEstado("Estado1957022658");
            _returnEstudianteInscripEdicionesVal1.setUrlVideo("UrlVideo683534570");
            _returnEstudianteInscripEdicionesVal1.setNota(Integer.valueOf(27760913));
            _returnEstudianteInscripEdicionesVal1.setFechaNota(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.172-03:00"));
            _returnEstudianteInscripEdiciones.add(_returnEstudianteInscripEdicionesVal1);
            _returnEstudiante.getInscripEdiciones().addAll(_returnEstudianteInscripEdiciones);
            java.util.List<edEXT.server.DtInscripcionPrograma> _returnEstudianteInscripProgramas = new java.util.ArrayList<edEXT.server.DtInscripcionPrograma>();
            edEXT.server.DtInscripcionPrograma _returnEstudianteInscripProgramasVal1 = new edEXT.server.DtInscripcionPrograma();
            _returnEstudianteInscripProgramasVal1.setPrograma("Programa2008373594");
            _returnEstudianteInscripProgramasVal1.setEstudiante("Estudiante882651985");
            _returnEstudianteInscripProgramasVal1.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.173-03:00"));
            _returnEstudianteInscripProgramasVal1.setEstado("Estado893564426");
            _returnEstudianteInscripProgramasVal1.setAprobada(false);
            _returnEstudianteInscripProgramasVal1.setFechaAprobada(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.174-03:00"));
            _returnEstudianteInscripProgramas.add(_returnEstudianteInscripProgramasVal1);
            _returnEstudiante.getInscripProgramas().addAll(_returnEstudianteInscripProgramas);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnEstudiantePuntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            edEXT.server.DtCursoPuntaje _returnEstudiantePuntajesVal1 = new edEXT.server.DtCursoPuntaje();
            _returnEstudiantePuntajesVal1.setCurso("Curso-966671223");
            _returnEstudiantePuntajesVal1.setEstudiante("Estudiante-1688840107");
            _returnEstudiantePuntajesVal1.setValor(Integer.valueOf(-524601138));
            _returnEstudiantePuntajes.add(_returnEstudiantePuntajesVal1);
            _returnEstudiante.getPuntajes().addAll(_returnEstudiantePuntajes);
            _return.setEstudiante(_returnEstudiante);
            edEXT.server.DtProgramaFormacion _returnPrograma = new edEXT.server.DtProgramaFormacion();
            _returnPrograma.setNombre("Nombre1438528113");
            _returnPrograma.setDescripcion("Descripcion1014058454");
            _returnPrograma.setFechaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.175-03:00"));
            _returnPrograma.setFechaFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.176-03:00"));
            _returnPrograma.setUrlImagen("UrlImagen-1360690619");
            java.util.List<java.lang.String> _returnProgramaCursos = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnProgramaCursosVal1 = "_returnProgramaCursosVal-97762593";
            _returnProgramaCursos.add(_returnProgramaCursosVal1);
            _returnPrograma.getCursos().addAll(_returnProgramaCursos);
            java.util.List<java.lang.String> _returnProgramaCategorias = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnProgramaCategoriasVal1 = "_returnProgramaCategoriasVal-1665826810";
            _returnProgramaCategorias.add(_returnProgramaCategoriasVal1);
            _returnPrograma.getCategorias().addAll(_returnProgramaCategorias);
            _return.setPrograma(_returnPrograma);
            edEXT.server.DtInscripcionPrograma _returnInscripcion = new edEXT.server.DtInscripcionPrograma();
            _returnInscripcion.setPrograma("Programa942281292");
            _returnInscripcion.setEstudiante("Estudiante-1451609408");
            _returnInscripcion.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.177-03:00"));
            _returnInscripcion.setEstado("Estado1421972105");
            _returnInscripcion.setAprobada(true);
            _returnInscripcion.setFechaAprobada(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.178-03:00"));
            _return.setInscripcion(_returnInscripcion);
            java.util.List<edEXT.server.DtInscripcionEdicion> _returnInscripcionesEdiciones = new java.util.ArrayList<edEXT.server.DtInscripcionEdicion>();
            edEXT.server.DtInscripcionEdicion _returnInscripcionesEdicionesVal1 = new edEXT.server.DtInscripcionEdicion();
            _returnInscripcionesEdicionesVal1.setEdicion("Edicion-683696538");
            _returnInscripcionesEdicionesVal1.setCurso("Curso1184348113");
            edEXT.server.DtInfoEstudiante _returnInscripcionesEdicionesVal1Estudiante = new edEXT.server.DtInfoEstudiante();
            _returnInscripcionesEdicionesVal1Estudiante.setApellido("Apellido-891539022");
            _returnInscripcionesEdicionesVal1Estudiante.setClave("Clave517743805");
            _returnInscripcionesEdicionesVal1Estudiante.setCorreoElectronico("CorreoElectronico-219322323");
            _returnInscripcionesEdicionesVal1Estudiante.setFechaNacimiento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.179-03:00"));
            _returnInscripcionesEdicionesVal1Estudiante.setNickname("Nickname-965206413");
            _returnInscripcionesEdicionesVal1Estudiante.setNombre("Nombre-2060234744");
            _returnInscripcionesEdicionesVal1Estudiante.setTipo("Tipo-412150408");
            _returnInscripcionesEdicionesVal1Estudiante.setUrlFoto("UrlFoto-126462332");
            java.util.List<edEXT.server.DtInscripcionEdicion> _returnInscripcionesEdicionesVal1EstudianteInscripEdiciones = new java.util.ArrayList<edEXT.server.DtInscripcionEdicion>();
            _returnInscripcionesEdicionesVal1Estudiante.getInscripEdiciones().addAll(_returnInscripcionesEdicionesVal1EstudianteInscripEdiciones);
            java.util.List<edEXT.server.DtInscripcionPrograma> _returnInscripcionesEdicionesVal1EstudianteInscripProgramas = new java.util.ArrayList<edEXT.server.DtInscripcionPrograma>();
            _returnInscripcionesEdicionesVal1Estudiante.getInscripProgramas().addAll(_returnInscripcionesEdicionesVal1EstudianteInscripProgramas);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnInscripcionesEdicionesVal1EstudiantePuntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnInscripcionesEdicionesVal1Estudiante.getPuntajes().addAll(_returnInscripcionesEdicionesVal1EstudiantePuntajes);
            _returnInscripcionesEdicionesVal1.setEstudiante(_returnInscripcionesEdicionesVal1Estudiante);
            _returnInscripcionesEdicionesVal1.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.181-03:00"));
            _returnInscripcionesEdicionesVal1.setEstado("Estado1230915927");
            _returnInscripcionesEdicionesVal1.setUrlVideo("UrlVideo-1846801287");
            _returnInscripcionesEdicionesVal1.setNota(Integer.valueOf(-343889501));
            _returnInscripcionesEdicionesVal1.setFechaNota(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.182-03:00"));
            _returnInscripcionesEdiciones.add(_returnInscripcionesEdicionesVal1);
            _return.getInscripcionesEdiciones().addAll(_returnInscripcionesEdiciones);
            _return.setError("Error-347805246");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#ingresarCurso(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, int arg4, int arg5, java.lang.String arg6, javax.xml.datatype.XMLGregorianCalendar arg7, java.lang.String arg8, java.util.List<java.lang.String> arg9, java.util.List<java.lang.String> arg10)*
     */
    public java.lang.String ingresarCurso(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, int arg4, int arg5, java.lang.String arg6, javax.xml.datatype.XMLGregorianCalendar arg7, java.lang.String arg8, java.util.List<java.lang.String> arg9, java.util.List<java.lang.String> arg10) {
        LOG.info("Executing operation ingresarCurso");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        System.out.println(arg8);
        System.out.println(arg9);
        System.out.println(arg10);
        try {
            java.lang.String _return = "_return1546399716";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#agregarCursoEdicionComentario(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2)*
     */
    public java.lang.String agregarCursoEdicionComentario(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2) {
        LOG.info("Executing operation agregarCursoEdicionComentario");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "_return1289740776";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#altaDocente(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, javax.xml.datatype.XMLGregorianCalendar arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7)*
     */
    public java.lang.String altaDocente(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, javax.xml.datatype.XMLGregorianCalendar arg4, java.lang.String arg5, java.lang.String arg6, java.lang.String arg7) {
        LOG.info("Executing operation altaDocente");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        try {
            java.lang.String _return = "_return825944847";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#seleccionarInstituto(java.lang.String arg0)*
     */
    public edEXT.server.DtInfoInstituto seleccionarInstituto(java.lang.String arg0) {
        LOG.info("Executing operation seleccionarInstituto");
        System.out.println(arg0);
        try {
            edEXT.server.DtInfoInstituto _return = new edEXT.server.DtInfoInstituto();
            _return.setNombre("Nombre1032640897");
            java.util.List<edEXT.server.DtInfoCurso> _returnCursos = new java.util.ArrayList<edEXT.server.DtInfoCurso>();
            edEXT.server.DtInfoCurso _returnCursosVal1 = new edEXT.server.DtInfoCurso();
            _returnCursosVal1.setNombre("Nombre-1066432130");
            _returnCursosVal1.setInstituto("Instituto-913265892");
            _returnCursosVal1.setDescripcion("Descripcion1783725188");
            _returnCursosVal1.setDuracion("Duracion-653771851");
            _returnCursosVal1.setCantidadHoras(1953982730);
            _returnCursosVal1.setCreditos(-2084277764);
            _returnCursosVal1.setUrl("Url1047628516");
            _returnCursosVal1.setFechaAlta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.190-03:00"));
            _returnCursosVal1.setUrlImagen("UrlImagen-394819329");
            _returnCursosVal1.setVisitas(Integer.valueOf(1479118002));
            _returnCursosVal1.setPuntaje(Float.valueOf(0.7058485f));
            java.util.List<java.lang.String> _returnCursosVal1Previas = new java.util.ArrayList<java.lang.String>();
            _returnCursosVal1.getPrevias().addAll(_returnCursosVal1Previas);
            java.util.List<edEXT.server.DtCursoEdicion> _returnCursosVal1Ediciones = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            _returnCursosVal1.getEdiciones().addAll(_returnCursosVal1Ediciones);
            java.util.List<edEXT.server.DtProgramaFormacion> _returnCursosVal1Programas = new java.util.ArrayList<edEXT.server.DtProgramaFormacion>();
            _returnCursosVal1.getProgramas().addAll(_returnCursosVal1Programas);
            java.util.List<java.lang.String> _returnCursosVal1Categorias = new java.util.ArrayList<java.lang.String>();
            _returnCursosVal1.getCategorias().addAll(_returnCursosVal1Categorias);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnCursosVal1Puntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnCursosVal1.getPuntajes().addAll(_returnCursosVal1Puntajes);
            _returnCursos.add(_returnCursosVal1);
            _return.getCursos().addAll(_returnCursos);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#modificarDocente(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, javax.xml.datatype.XMLGregorianCalendar arg3, java.lang.String arg4, java.lang.String arg5)*
     */
    public java.lang.String modificarDocente(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, javax.xml.datatype.XMLGregorianCalendar arg3, java.lang.String arg4, java.lang.String arg5) {
        LOG.info("Executing operation modificarDocente");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        try {
            java.lang.String _return = "_return-178443121";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#agregarCursoProgramaFormacion(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String agregarCursoProgramaFormacion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation agregarCursoProgramaFormacion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-2060643773";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#modificarEstudiante(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, javax.xml.datatype.XMLGregorianCalendar arg3, java.lang.String arg4)*
     */
    public java.lang.String modificarEstudiante(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, javax.xml.datatype.XMLGregorianCalendar arg3, java.lang.String arg4) {
        LOG.info("Executing operation modificarEstudiante");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            java.lang.String _return = "_return427189733";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#agregarRespuestaCursoEdicionComentario(long arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3)*
     */
    public java.lang.String agregarRespuestaCursoEdicionComentario(long arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) {
        LOG.info("Executing operation agregarRespuestaCursoEdicionComentario");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.lang.String _return = "_return458118602";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarCursosEstudiante(java.lang.String arg0)*
     */
    public edEXT.server.DtListaCursos listarCursosEstudiante(java.lang.String arg0) {
        LOG.info("Executing operation listarCursosEstudiante");
        System.out.println(arg0);
        try {
            edEXT.server.DtListaCursos _return = new edEXT.server.DtListaCursos();
            java.util.List<edEXT.server.DtInfoCurso> _returnLista = new java.util.ArrayList<edEXT.server.DtInfoCurso>();
            edEXT.server.DtInfoCurso _returnListaVal1 = new edEXT.server.DtInfoCurso();
            _returnListaVal1.setNombre("Nombre-866987255");
            _returnListaVal1.setInstituto("Instituto-10372233");
            _returnListaVal1.setDescripcion("Descripcion867638689");
            _returnListaVal1.setDuracion("Duracion366258271");
            _returnListaVal1.setCantidadHoras(-918048038);
            _returnListaVal1.setCreditos(-979759170);
            _returnListaVal1.setUrl("Url540088564");
            _returnListaVal1.setFechaAlta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.199-03:00"));
            _returnListaVal1.setUrlImagen("UrlImagen344543503");
            _returnListaVal1.setVisitas(Integer.valueOf(1166427573));
            _returnListaVal1.setPuntaje(Float.valueOf(0.016601682f));
            java.util.List<java.lang.String> _returnListaVal1Previas = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getPrevias().addAll(_returnListaVal1Previas);
            java.util.List<edEXT.server.DtCursoEdicion> _returnListaVal1Ediciones = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            _returnListaVal1.getEdiciones().addAll(_returnListaVal1Ediciones);
            java.util.List<edEXT.server.DtProgramaFormacion> _returnListaVal1Programas = new java.util.ArrayList<edEXT.server.DtProgramaFormacion>();
            _returnListaVal1.getProgramas().addAll(_returnListaVal1Programas);
            java.util.List<java.lang.String> _returnListaVal1Categorias = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getCategorias().addAll(_returnListaVal1Categorias);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnListaVal1Puntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnListaVal1.getPuntajes().addAll(_returnListaVal1Puntajes);
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarDocentesInstituto(java.lang.String arg0)*
     */
    public edEXT.server.DtListaString listarDocentesInstituto(java.lang.String arg0) {
        LOG.info("Executing operation listarDocentesInstituto");
        System.out.println(arg0);
        try {
            edEXT.server.DtListaString _return = new edEXT.server.DtListaString();
            java.util.List<java.lang.String> _returnLista = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnListaVal1 = "_returnListaVal2142159295";
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#tramitarCertificadoProgramaFormacion(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String tramitarCertificadoProgramaFormacion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation tramitarCertificadoProgramaFormacion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1596658925";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#seleccionarCategoria(java.lang.String arg0)*
     */
    public edEXT.server.DtInfoCategoria seleccionarCategoria(java.lang.String arg0) {
        LOG.info("Executing operation seleccionarCategoria");
        System.out.println(arg0);
        try {
            edEXT.server.DtInfoCategoria _return = new edEXT.server.DtInfoCategoria();
            _return.setNombre("Nombre246434524");
            java.util.List<edEXT.server.DtInfoCurso> _returnCursos = new java.util.ArrayList<edEXT.server.DtInfoCurso>();
            edEXT.server.DtInfoCurso _returnCursosVal1 = new edEXT.server.DtInfoCurso();
            _returnCursosVal1.setNombre("Nombre-1811483893");
            _returnCursosVal1.setInstituto("Instituto768972733");
            _returnCursosVal1.setDescripcion("Descripcion333686839");
            _returnCursosVal1.setDuracion("Duracion-483006014");
            _returnCursosVal1.setCantidadHoras(687129175);
            _returnCursosVal1.setCreditos(1121832387);
            _returnCursosVal1.setUrl("Url1003380430");
            _returnCursosVal1.setFechaAlta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.203-03:00"));
            _returnCursosVal1.setUrlImagen("UrlImagen474602225");
            _returnCursosVal1.setVisitas(Integer.valueOf(1984173605));
            _returnCursosVal1.setPuntaje(Float.valueOf(0.96801704f));
            java.util.List<java.lang.String> _returnCursosVal1Previas = new java.util.ArrayList<java.lang.String>();
            _returnCursosVal1.getPrevias().addAll(_returnCursosVal1Previas);
            java.util.List<edEXT.server.DtCursoEdicion> _returnCursosVal1Ediciones = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            _returnCursosVal1.getEdiciones().addAll(_returnCursosVal1Ediciones);
            java.util.List<edEXT.server.DtProgramaFormacion> _returnCursosVal1Programas = new java.util.ArrayList<edEXT.server.DtProgramaFormacion>();
            _returnCursosVal1.getProgramas().addAll(_returnCursosVal1Programas);
            java.util.List<java.lang.String> _returnCursosVal1Categorias = new java.util.ArrayList<java.lang.String>();
            _returnCursosVal1.getCategorias().addAll(_returnCursosVal1Categorias);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnCursosVal1Puntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnCursosVal1.getPuntajes().addAll(_returnCursosVal1Puntajes);
            _returnCursos.add(_returnCursosVal1);
            _return.getCursos().addAll(_returnCursos);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#getDtInfoCursoEdicionVigente(java.lang.String arg0)*
     */
    public edEXT.server.DtCursoEdicion getDtInfoCursoEdicionVigente(java.lang.String arg0) {
        LOG.info("Executing operation getDtInfoCursoEdicionVigente");
        System.out.println(arg0);
        try {
            edEXT.server.DtCursoEdicion _return = new edEXT.server.DtCursoEdicion();
            _return.setNombre("Nombre1634861797");
            _return.setInstituto("Instituto-1787512018");
            _return.setCurso("Curso33625681");
            _return.setFechaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.206-03:00"));
            _return.setFechaFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.207-03:00"));
            _return.setCupo(-525235672);
            _return.setFechaRegistro(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.208-03:00"));
            _return.setUrlImagen("UrlImagen-1565983044");
            _return.setVigente(true);
            _return.setFinalizada(false);
            java.util.List<java.lang.String> _returnDictadoPor = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnDictadoPorVal1 = "_returnDictadoPorVal-1219413852";
            _returnDictadoPor.add(_returnDictadoPorVal1);
            _return.getDictadoPor().addAll(_returnDictadoPor);
            java.util.List<edEXT.server.DtInfoDocente> _returnDocentes = new java.util.ArrayList<edEXT.server.DtInfoDocente>();
            edEXT.server.DtInfoDocente _returnDocentesVal1 = new edEXT.server.DtInfoDocente();
            _returnDocentesVal1.setApellido("Apellido1474109041");
            _returnDocentesVal1.setClave("Clave1523755930");
            _returnDocentesVal1.setCorreoElectronico("CorreoElectronico1056704875");
            _returnDocentesVal1.setFechaNacimiento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.209-03:00"));
            _returnDocentesVal1.setNickname("Nickname-51353683");
            _returnDocentesVal1.setNombre("Nombre673186558");
            _returnDocentesVal1.setTipo("Tipo-1895680454");
            _returnDocentesVal1.setUrlFoto("UrlFoto-881085946");
            _returnDocentesVal1.setInstituto("Instituto-1994963615");
            java.util.List<edEXT.server.DtInfoCurso> _returnDocentesVal1Cursos = new java.util.ArrayList<edEXT.server.DtInfoCurso>();
            _returnDocentesVal1.getCursos().addAll(_returnDocentesVal1Cursos);
            java.util.List<edEXT.server.DtCursoEdicion> _returnDocentesVal1Ediciones = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            _returnDocentesVal1.getEdiciones().addAll(_returnDocentesVal1Ediciones);
            java.util.List<edEXT.server.DtProgramaFormacion> _returnDocentesVal1Programas = new java.util.ArrayList<edEXT.server.DtProgramaFormacion>();
            _returnDocentesVal1.getProgramas().addAll(_returnDocentesVal1Programas);
            _returnDocentes.add(_returnDocentesVal1);
            _return.getDocentes().addAll(_returnDocentes);
            java.util.List<edEXT.server.DtInscripcionEdicion> _returnInscripciones = new java.util.ArrayList<edEXT.server.DtInscripcionEdicion>();
            edEXT.server.DtInscripcionEdicion _returnInscripcionesVal1 = new edEXT.server.DtInscripcionEdicion();
            _returnInscripcionesVal1.setEdicion("Edicion-1620881307");
            _returnInscripcionesVal1.setCurso("Curso155202254");
            edEXT.server.DtInfoEstudiante _returnInscripcionesVal1Estudiante = new edEXT.server.DtInfoEstudiante();
            _returnInscripcionesVal1Estudiante.setApellido("Apellido-582345791");
            _returnInscripcionesVal1Estudiante.setClave("Clave-189447211");
            _returnInscripcionesVal1Estudiante.setCorreoElectronico("CorreoElectronico508103465");
            _returnInscripcionesVal1Estudiante.setFechaNacimiento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.210-03:00"));
            _returnInscripcionesVal1Estudiante.setNickname("Nickname191934746");
            _returnInscripcionesVal1Estudiante.setNombre("Nombre1434695846");
            _returnInscripcionesVal1Estudiante.setTipo("Tipo-91751403");
            _returnInscripcionesVal1Estudiante.setUrlFoto("UrlFoto362273024");
            java.util.List<edEXT.server.DtInscripcionEdicion> _returnInscripcionesVal1EstudianteInscripEdiciones = new java.util.ArrayList<edEXT.server.DtInscripcionEdicion>();
            _returnInscripcionesVal1Estudiante.getInscripEdiciones().addAll(_returnInscripcionesVal1EstudianteInscripEdiciones);
            java.util.List<edEXT.server.DtInscripcionPrograma> _returnInscripcionesVal1EstudianteInscripProgramas = new java.util.ArrayList<edEXT.server.DtInscripcionPrograma>();
            _returnInscripcionesVal1Estudiante.getInscripProgramas().addAll(_returnInscripcionesVal1EstudianteInscripProgramas);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnInscripcionesVal1EstudiantePuntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnInscripcionesVal1Estudiante.getPuntajes().addAll(_returnInscripcionesVal1EstudiantePuntajes);
            _returnInscripcionesVal1.setEstudiante(_returnInscripcionesVal1Estudiante);
            _returnInscripcionesVal1.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.212-03:00"));
            _returnInscripcionesVal1.setEstado("Estado-324833485");
            _returnInscripcionesVal1.setUrlVideo("UrlVideo-1630594750");
            _returnInscripcionesVal1.setNota(Integer.valueOf(-320946840));
            _returnInscripcionesVal1.setFechaNota(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.213-03:00"));
            _returnInscripciones.add(_returnInscripcionesVal1);
            _return.getInscripciones().addAll(_returnInscripciones);
            java.util.List<edEXT.server.DtCursoEdicionComentario> _returnComentarios = new java.util.ArrayList<edEXT.server.DtCursoEdicionComentario>();
            edEXT.server.DtCursoEdicionComentario _returnComentariosVal1 = new edEXT.server.DtCursoEdicionComentario();
            _returnComentariosVal1.setId(-1736673373739400091l);
            _returnComentariosVal1.setEdicion("Edicion1996048320");
            _returnComentariosVal1.setEstudiante("Estudiante1433488600");
            _returnComentariosVal1.setTexto("Texto-305527373");
            _returnComentariosVal1.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.214-03:00"));
            _returnComentariosVal1.setIdPadre(702797212288303155l);
            java.util.List<edEXT.server.DtCursoEdicionComentario> _returnComentariosVal1Respuestas = new java.util.ArrayList<edEXT.server.DtCursoEdicionComentario>();
            _returnComentariosVal1.getRespuestas().addAll(_returnComentariosVal1Respuestas);
            _returnComentarios.add(_returnComentariosVal1);
            _return.getComentarios().addAll(_returnComentarios);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#altaCategoria(java.lang.String arg0)*
     */
    public java.lang.String altaCategoria(java.lang.String arg0) {
        LOG.info("Executing operation altaCategoria");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1973118736";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#desitirInscripcionEdicion(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String desitirInscripcionEdicion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation desitirInscripcionEdicion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-754165296";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#getDtInfoCurso(java.lang.String arg0)*
     */
    public edEXT.server.DtInfoCurso getDtInfoCurso(java.lang.String arg0) {
        LOG.info("Executing operation getDtInfoCurso");
        System.out.println(arg0);
        try {
            edEXT.server.DtInfoCurso _return = new edEXT.server.DtInfoCurso();
            _return.setNombre("Nombre80739437");
            _return.setInstituto("Instituto-376169934");
            _return.setDescripcion("Descripcion1409312199");
            _return.setDuracion("Duracion1765680038");
            _return.setCantidadHoras(1180267885);
            _return.setCreditos(1788655529);
            _return.setUrl("Url-985320131");
            _return.setFechaAlta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.218-03:00"));
            _return.setUrlImagen("UrlImagen-1528184008");
            _return.setVisitas(Integer.valueOf(921621348));
            _return.setPuntaje(Float.valueOf(0.3885963f));
            java.util.List<java.lang.String> _returnPrevias = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnPreviasVal1 = "_returnPreviasVal-960368764";
            _returnPrevias.add(_returnPreviasVal1);
            _return.getPrevias().addAll(_returnPrevias);
            java.util.List<edEXT.server.DtCursoEdicion> _returnEdiciones = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            edEXT.server.DtCursoEdicion _returnEdicionesVal1 = new edEXT.server.DtCursoEdicion();
            _returnEdicionesVal1.setNombre("Nombre-2120072652");
            _returnEdicionesVal1.setInstituto("Instituto832618954");
            _returnEdicionesVal1.setCurso("Curso-1419618798");
            _returnEdicionesVal1.setFechaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.219-03:00"));
            _returnEdicionesVal1.setFechaFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.220-03:00"));
            _returnEdicionesVal1.setCupo(-352514078);
            _returnEdicionesVal1.setFechaRegistro(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.221-03:00"));
            _returnEdicionesVal1.setUrlImagen("UrlImagen766737252");
            _returnEdicionesVal1.setVigente(false);
            _returnEdicionesVal1.setFinalizada(true);
            java.util.List<java.lang.String> _returnEdicionesVal1DictadoPor = new java.util.ArrayList<java.lang.String>();
            _returnEdicionesVal1.getDictadoPor().addAll(_returnEdicionesVal1DictadoPor);
            java.util.List<edEXT.server.DtInfoDocente> _returnEdicionesVal1Docentes = new java.util.ArrayList<edEXT.server.DtInfoDocente>();
            _returnEdicionesVal1.getDocentes().addAll(_returnEdicionesVal1Docentes);
            java.util.List<edEXT.server.DtInscripcionEdicion> _returnEdicionesVal1Inscripciones = new java.util.ArrayList<edEXT.server.DtInscripcionEdicion>();
            _returnEdicionesVal1.getInscripciones().addAll(_returnEdicionesVal1Inscripciones);
            java.util.List<edEXT.server.DtCursoEdicionComentario> _returnEdicionesVal1Comentarios = new java.util.ArrayList<edEXT.server.DtCursoEdicionComentario>();
            _returnEdicionesVal1.getComentarios().addAll(_returnEdicionesVal1Comentarios);
            _returnEdiciones.add(_returnEdicionesVal1);
            _return.getEdiciones().addAll(_returnEdiciones);
            java.util.List<edEXT.server.DtProgramaFormacion> _returnProgramas = new java.util.ArrayList<edEXT.server.DtProgramaFormacion>();
            edEXT.server.DtProgramaFormacion _returnProgramasVal1 = new edEXT.server.DtProgramaFormacion();
            _returnProgramasVal1.setNombre("Nombre1589467572");
            _returnProgramasVal1.setDescripcion("Descripcion57197930");
            _returnProgramasVal1.setFechaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.223-03:00"));
            _returnProgramasVal1.setFechaFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.223-03:00"));
            _returnProgramasVal1.setUrlImagen("UrlImagen-1435764375");
            java.util.List<java.lang.String> _returnProgramasVal1Cursos = new java.util.ArrayList<java.lang.String>();
            _returnProgramasVal1.getCursos().addAll(_returnProgramasVal1Cursos);
            java.util.List<java.lang.String> _returnProgramasVal1Categorias = new java.util.ArrayList<java.lang.String>();
            _returnProgramasVal1.getCategorias().addAll(_returnProgramasVal1Categorias);
            _returnProgramas.add(_returnProgramasVal1);
            _return.getProgramas().addAll(_returnProgramas);
            java.util.List<java.lang.String> _returnCategorias = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnCategoriasVal1 = "_returnCategoriasVal783595437";
            _returnCategorias.add(_returnCategoriasVal1);
            _return.getCategorias().addAll(_returnCategorias);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnPuntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            edEXT.server.DtCursoPuntaje _returnPuntajesVal1 = new edEXT.server.DtCursoPuntaje();
            _returnPuntajesVal1.setCurso("Curso-776316491");
            _returnPuntajesVal1.setEstudiante("Estudiante1392972972");
            _returnPuntajesVal1.setValor(Integer.valueOf(-1557131416));
            _returnPuntajes.add(_returnPuntajesVal1);
            _return.getPuntajes().addAll(_returnPuntajes);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#inscribirProgramaFormacion(java.lang.String arg0, java.lang.String arg1, javax.xml.datatype.XMLGregorianCalendar arg2)*
     */
    public java.lang.String inscribirProgramaFormacion(java.lang.String arg0, java.lang.String arg1, javax.xml.datatype.XMLGregorianCalendar arg2) {
        LOG.info("Executing operation inscribirProgramaFormacion");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.lang.String _return = "_return-757344146";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#crearProgramaFormacion(java.lang.String arg0, java.lang.String arg1, javax.xml.datatype.XMLGregorianCalendar arg2, javax.xml.datatype.XMLGregorianCalendar arg3, java.lang.String arg4)*
     */
    public java.lang.String crearProgramaFormacion(java.lang.String arg0, java.lang.String arg1, javax.xml.datatype.XMLGregorianCalendar arg2, javax.xml.datatype.XMLGregorianCalendar arg3, java.lang.String arg4) {
        LOG.info("Executing operation crearProgramaFormacion");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            java.lang.String _return = "_return1040004992";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarCursosVisitas()*
     */
    public edEXT.server.DtListaCursos listarCursosVisitas() {
        LOG.info("Executing operation listarCursosVisitas");
        try {
            edEXT.server.DtListaCursos _return = new edEXT.server.DtListaCursos();
            java.util.List<edEXT.server.DtInfoCurso> _returnLista = new java.util.ArrayList<edEXT.server.DtInfoCurso>();
            edEXT.server.DtInfoCurso _returnListaVal1 = new edEXT.server.DtInfoCurso();
            _returnListaVal1.setNombre("Nombre-520959860");
            _returnListaVal1.setInstituto("Instituto717034344");
            _returnListaVal1.setDescripcion("Descripcion989111565");
            _returnListaVal1.setDuracion("Duracion1908317011");
            _returnListaVal1.setCantidadHoras(-1102538788);
            _returnListaVal1.setCreditos(-969147696);
            _returnListaVal1.setUrl("Url-553269255");
            _returnListaVal1.setFechaAlta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.230-03:00"));
            _returnListaVal1.setUrlImagen("UrlImagen689351701");
            _returnListaVal1.setVisitas(Integer.valueOf(-88846191));
            _returnListaVal1.setPuntaje(Float.valueOf(0.07243729f));
            java.util.List<java.lang.String> _returnListaVal1Previas = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getPrevias().addAll(_returnListaVal1Previas);
            java.util.List<edEXT.server.DtCursoEdicion> _returnListaVal1Ediciones = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            _returnListaVal1.getEdiciones().addAll(_returnListaVal1Ediciones);
            java.util.List<edEXT.server.DtProgramaFormacion> _returnListaVal1Programas = new java.util.ArrayList<edEXT.server.DtProgramaFormacion>();
            _returnListaVal1.getProgramas().addAll(_returnListaVal1Programas);
            java.util.List<java.lang.String> _returnListaVal1Categorias = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getCategorias().addAll(_returnListaVal1Categorias);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnListaVal1Puntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnListaVal1.getPuntajes().addAll(_returnListaVal1Puntajes);
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#rechazarInscripcionEdicion(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String rechazarInscripcionEdicion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation rechazarInscripcionEdicion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1394226790";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarCursosString()*
     */
    public edEXT.server.DtListaString listarCursosString() {
        LOG.info("Executing operation listarCursosString");
        try {
            edEXT.server.DtListaString _return = new edEXT.server.DtListaString();
            java.util.List<java.lang.String> _returnLista = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnListaVal1 = "_returnListaVal-1767872103";
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#agregarCategoriaCurso(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String agregarCategoriaCurso(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation agregarCategoriaCurso");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1010344266";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#calificarInscripcionEdicion(java.lang.String arg0, java.lang.String arg1, java.lang.Integer arg2, javax.xml.datatype.XMLGregorianCalendar arg3)*
     */
    public java.lang.String calificarInscripcionEdicion(java.lang.String arg0, java.lang.String arg1, java.lang.Integer arg2, javax.xml.datatype.XMLGregorianCalendar arg3) {
        LOG.info("Executing operation calificarInscripcionEdicion");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.lang.String _return = "_return-632974623";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarCursosInstitutoString(java.lang.String arg0)*
     */
    public edEXT.server.DtListaString listarCursosInstitutoString(java.lang.String arg0) {
        LOG.info("Executing operation listarCursosInstitutoString");
        System.out.println(arg0);
        try {
            edEXT.server.DtListaString _return = new edEXT.server.DtListaString();
            java.util.List<java.lang.String> _returnLista = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnListaVal1 = "_returnListaVal1870525021";
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#agregarDocenteEdicionCurso(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String agregarDocenteEdicionCurso(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation agregarDocenteEdicionCurso");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return880928548";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#inscribirEdicionCurso(java.lang.String arg0, java.lang.String arg1, javax.xml.datatype.XMLGregorianCalendar arg2, java.lang.String arg3)*
     */
    public java.lang.String inscribirEdicionCurso(java.lang.String arg0, java.lang.String arg1, javax.xml.datatype.XMLGregorianCalendar arg2, java.lang.String arg3) {
        LOG.info("Executing operation inscribirEdicionCurso");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.lang.String _return = "_return867978914";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarCursosCategoria(java.lang.String arg0)*
     */
    public edEXT.server.DtListaCursos listarCursosCategoria(java.lang.String arg0) {
        LOG.info("Executing operation listarCursosCategoria");
        System.out.println(arg0);
        try {
            edEXT.server.DtListaCursos _return = new edEXT.server.DtListaCursos();
            java.util.List<edEXT.server.DtInfoCurso> _returnLista = new java.util.ArrayList<edEXT.server.DtInfoCurso>();
            edEXT.server.DtInfoCurso _returnListaVal1 = new edEXT.server.DtInfoCurso();
            _returnListaVal1.setNombre("Nombre-437584974");
            _returnListaVal1.setInstituto("Instituto-1550796273");
            _returnListaVal1.setDescripcion("Descripcion509553196");
            _returnListaVal1.setDuracion("Duracion649313900");
            _returnListaVal1.setCantidadHoras(-1229855037);
            _returnListaVal1.setCreditos(1789352047);
            _returnListaVal1.setUrl("Url-1865043614");
            _returnListaVal1.setFechaAlta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.238-03:00"));
            _returnListaVal1.setUrlImagen("UrlImagen1833595551");
            _returnListaVal1.setVisitas(Integer.valueOf(351775341));
            _returnListaVal1.setPuntaje(Float.valueOf(0.48021376f));
            java.util.List<java.lang.String> _returnListaVal1Previas = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getPrevias().addAll(_returnListaVal1Previas);
            java.util.List<edEXT.server.DtCursoEdicion> _returnListaVal1Ediciones = new java.util.ArrayList<edEXT.server.DtCursoEdicion>();
            _returnListaVal1.getEdiciones().addAll(_returnListaVal1Ediciones);
            java.util.List<edEXT.server.DtProgramaFormacion> _returnListaVal1Programas = new java.util.ArrayList<edEXT.server.DtProgramaFormacion>();
            _returnListaVal1.getProgramas().addAll(_returnListaVal1Programas);
            java.util.List<java.lang.String> _returnListaVal1Categorias = new java.util.ArrayList<java.lang.String>();
            _returnListaVal1.getCategorias().addAll(_returnListaVal1Categorias);
            java.util.List<edEXT.server.DtCursoPuntaje> _returnListaVal1Puntajes = new java.util.ArrayList<edEXT.server.DtCursoPuntaje>();
            _returnListaVal1.getPuntajes().addAll(_returnListaVal1Puntajes);
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see edEXT.server.Servidor#listarDocentes()*
     */
    public edEXT.server.DtListaString listarDocentes() {
        LOG.info("Executing operation listarDocentes");
        try {
            edEXT.server.DtListaString _return = new edEXT.server.DtListaString();
            java.util.List<java.lang.String> _returnLista = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnListaVal1 = "_returnListaVal1216014322";
            _returnLista.add(_returnListaVal1);
            _return.getLista().addAll(_returnLista);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
