package edEXT.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-21T01:20:03.291-03:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "ServidorService",
                  wsdlLocation = "http://localhost:9122/edEXTServidor?wsdl",
                  targetNamespace = "http://server.edEXT/")
public class ServidorService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.edEXT/", "ServidorService");
    public final static QName ServidorPort = new QName("http://server.edEXT/", "ServidorPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9122/edEXTServidor?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServidorService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:9122/edEXTServidor?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServidorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServidorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServidorService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServidorService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServidorService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServidorService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Servidor
     */
    @WebEndpoint(name = "ServidorPort")
    public Servidor getServidorPort() {
        return super.getPort(ServidorPort, Servidor.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Servidor
     */
    @WebEndpoint(name = "ServidorPort")
    public Servidor getServidorPort(WebServiceFeature... features) {
        return super.getPort(ServidorPort, Servidor.class, features);
    }

}
