package edEXT.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-21T01:20:03.241-03:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://server.edEXT/", name = "Servidor")
@XmlSeeAlso({ObjectFactory.class})
public interface Servidor {

    @WebMethod
    @RequestWrapper(localName = "listarProgramasFormacionString", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarProgramasFormacionString")
    @ResponseWrapper(localName = "listarProgramasFormacionStringResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarProgramasFormacionStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaString listarProgramasFormacionString()
;

    @WebMethod
    @RequestWrapper(localName = "altaInstituto", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AltaInstituto")
    @ResponseWrapper(localName = "altaInstitutoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AltaInstitutoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String altaInstituto(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "incrementarVisitaCurso", targetNamespace = "http://server.edEXT/", className = "edEXT.server.IncrementarVisitaCurso")
    @ResponseWrapper(localName = "incrementarVisitaCursoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.IncrementarVisitaCursoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Integer incrementarVisitaCurso(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "seleccionarUsuario", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarUsuario")
    @ResponseWrapper(localName = "seleccionarUsuarioResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtInfoUsuario seleccionarUsuario(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "listarCursosCategoriaString", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosCategoriaString")
    @ResponseWrapper(localName = "listarCursosCategoriaStringResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosCategoriaStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaString listarCursosCategoriaString(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "puntuarCurso", targetNamespace = "http://server.edEXT/", className = "edEXT.server.PuntuarCurso")
    @ResponseWrapper(localName = "puntuarCursoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.PuntuarCursoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String puntuarCurso(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Integer arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getDtInfoCursoEdicion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.GetDtInfoCursoEdicion")
    @ResponseWrapper(localName = "getDtInfoCursoEdicionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.GetDtInfoCursoEdicionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtCursoEdicion getDtInfoCursoEdicion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "agregarPreviaCurso", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarPreviaCurso")
    @ResponseWrapper(localName = "agregarPreviaCursoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarPreviaCursoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String agregarPreviaCurso(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "listarCategorias", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCategorias")
    @ResponseWrapper(localName = "listarCategoriasResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCategoriasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaString listarCategorias()
;

    @WebMethod
    @RequestWrapper(localName = "listarUsuarios", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarUsuarios")
    @ResponseWrapper(localName = "listarUsuariosResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarUsuariosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaUsuarios listarUsuarios()
;

    @WebMethod
    @RequestWrapper(localName = "finalizarEdicion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.FinalizarEdicion")
    @ResponseWrapper(localName = "finalizarEdicionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.FinalizarEdicionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String finalizarEdicion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "seleccionarUsuarioCorreo", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarUsuarioCorreo")
    @ResponseWrapper(localName = "seleccionarUsuarioCorreoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarUsuarioCorreoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtInfoUsuario seleccionarUsuarioCorreo(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "altaEstudiante", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AltaEstudiante")
    @ResponseWrapper(localName = "altaEstudianteResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AltaEstudianteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String altaEstudiante(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    );

    @WebMethod
    @RequestWrapper(localName = "listarEstudiantes", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarEstudiantes")
    @ResponseWrapper(localName = "listarEstudiantesResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarEstudiantesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaString listarEstudiantes()
;

    @WebMethod
    @RequestWrapper(localName = "listarCursos", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursos")
    @ResponseWrapper(localName = "listarCursosResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaCursos listarCursos()
;

    @WebMethod
    @RequestWrapper(localName = "listarInstitutos", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarInstitutos")
    @ResponseWrapper(localName = "listarInstitutosResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarInstitutosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaString listarInstitutos()
;

    @WebMethod
    @RequestWrapper(localName = "aceptarInscripcionEdicion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AceptarInscripcionEdicion")
    @ResponseWrapper(localName = "aceptarInscripcionEdicionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AceptarInscripcionEdicionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String aceptarInscripcionEdicion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "listarCursosInstituto", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosInstituto")
    @ResponseWrapper(localName = "listarCursosInstitutoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosInstitutoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaCursos listarCursosInstituto(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "crearEdicionCurso", targetNamespace = "http://server.edEXT/", className = "edEXT.server.CrearEdicionCurso")
    @ResponseWrapper(localName = "crearEdicionCursoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.CrearEdicionCursoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearEdicionCurso(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.util.List<java.lang.String> arg7
    );

    @WebMethod
    @RequestWrapper(localName = "seleccionarCurso", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarCurso")
    @ResponseWrapper(localName = "seleccionarCursoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarCursoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaCursoEdiciones seleccionarCurso(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "seleccionarProgramaFormacion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarProgramaFormacion")
    @ResponseWrapper(localName = "seleccionarProgramaFormacionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarProgramaFormacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtProgramaFormacion seleccionarProgramaFormacion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "obtenerCertificadoProgramaFormacion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ObtenerCertificadoProgramaFormacion")
    @ResponseWrapper(localName = "obtenerCertificadoProgramaFormacionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ObtenerCertificadoProgramaFormacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtCertificadoProgramaFormacion obtenerCertificadoProgramaFormacion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "ingresarCurso", targetNamespace = "http://server.edEXT/", className = "edEXT.server.IngresarCurso")
    @ResponseWrapper(localName = "ingresarCursoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.IngresarCursoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String ingresarCurso(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        java.util.List<java.lang.String> arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        java.util.List<java.lang.String> arg10
    );

    @WebMethod
    @RequestWrapper(localName = "agregarCursoEdicionComentario", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarCursoEdicionComentario")
    @ResponseWrapper(localName = "agregarCursoEdicionComentarioResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarCursoEdicionComentarioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String agregarCursoEdicionComentario(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "altaDocente", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AltaDocente")
    @ResponseWrapper(localName = "altaDocenteResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AltaDocenteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String altaDocente(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7
    );

    @WebMethod
    @RequestWrapper(localName = "seleccionarInstituto", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarInstituto")
    @ResponseWrapper(localName = "seleccionarInstitutoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarInstitutoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtInfoInstituto seleccionarInstituto(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "modificarDocente", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ModificarDocente")
    @ResponseWrapper(localName = "modificarDocenteResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ModificarDocenteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String modificarDocente(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    );

    @WebMethod
    @RequestWrapper(localName = "agregarCursoProgramaFormacion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarCursoProgramaFormacion")
    @ResponseWrapper(localName = "agregarCursoProgramaFormacionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarCursoProgramaFormacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String agregarCursoProgramaFormacion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "modificarEstudiante", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ModificarEstudiante")
    @ResponseWrapper(localName = "modificarEstudianteResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ModificarEstudianteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String modificarEstudiante(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @RequestWrapper(localName = "agregarRespuestaCursoEdicionComentario", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarRespuestaCursoEdicionComentario")
    @ResponseWrapper(localName = "agregarRespuestaCursoEdicionComentarioResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarRespuestaCursoEdicionComentarioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String agregarRespuestaCursoEdicionComentario(

        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "listarCursosEstudiante", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosEstudiante")
    @ResponseWrapper(localName = "listarCursosEstudianteResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosEstudianteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaCursos listarCursosEstudiante(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "listarDocentesInstituto", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarDocentesInstituto")
    @ResponseWrapper(localName = "listarDocentesInstitutoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarDocentesInstitutoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaString listarDocentesInstituto(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "tramitarCertificadoProgramaFormacion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.TramitarCertificadoProgramaFormacion")
    @ResponseWrapper(localName = "tramitarCertificadoProgramaFormacionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.TramitarCertificadoProgramaFormacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String tramitarCertificadoProgramaFormacion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "seleccionarCategoria", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarCategoria")
    @ResponseWrapper(localName = "seleccionarCategoriaResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.SeleccionarCategoriaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtInfoCategoria seleccionarCategoria(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getDtInfoCursoEdicionVigente", targetNamespace = "http://server.edEXT/", className = "edEXT.server.GetDtInfoCursoEdicionVigente")
    @ResponseWrapper(localName = "getDtInfoCursoEdicionVigenteResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.GetDtInfoCursoEdicionVigenteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtCursoEdicion getDtInfoCursoEdicionVigente(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "altaCategoria", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AltaCategoria")
    @ResponseWrapper(localName = "altaCategoriaResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AltaCategoriaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String altaCategoria(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "desitirInscripcionEdicion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.DesitirInscripcionEdicion")
    @ResponseWrapper(localName = "desitirInscripcionEdicionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.DesitirInscripcionEdicionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String desitirInscripcionEdicion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getDtInfoCurso", targetNamespace = "http://server.edEXT/", className = "edEXT.server.GetDtInfoCurso")
    @ResponseWrapper(localName = "getDtInfoCursoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.GetDtInfoCursoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtInfoCurso getDtInfoCurso(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "inscribirProgramaFormacion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.InscribirProgramaFormacion")
    @ResponseWrapper(localName = "inscribirProgramaFormacionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.InscribirProgramaFormacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String inscribirProgramaFormacion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg2
    );

    @WebMethod
    @RequestWrapper(localName = "crearProgramaFormacion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.CrearProgramaFormacion")
    @ResponseWrapper(localName = "crearProgramaFormacionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.CrearProgramaFormacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String crearProgramaFormacion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @RequestWrapper(localName = "listarCursosVisitas", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosVisitas")
    @ResponseWrapper(localName = "listarCursosVisitasResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosVisitasResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaCursos listarCursosVisitas()
;

    @WebMethod
    @RequestWrapper(localName = "rechazarInscripcionEdicion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.RechazarInscripcionEdicion")
    @ResponseWrapper(localName = "rechazarInscripcionEdicionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.RechazarInscripcionEdicionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String rechazarInscripcionEdicion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "listarCursosString", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosString")
    @ResponseWrapper(localName = "listarCursosStringResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaString listarCursosString()
;

    @WebMethod
    @RequestWrapper(localName = "agregarCategoriaCurso", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarCategoriaCurso")
    @ResponseWrapper(localName = "agregarCategoriaCursoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarCategoriaCursoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String agregarCategoriaCurso(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "calificarInscripcionEdicion", targetNamespace = "http://server.edEXT/", className = "edEXT.server.CalificarInscripcionEdicion")
    @ResponseWrapper(localName = "calificarInscripcionEdicionResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.CalificarInscripcionEdicionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String calificarInscripcionEdicion(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Integer arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg3
    );

    @WebMethod
    @RequestWrapper(localName = "listarCursosInstitutoString", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosInstitutoString")
    @ResponseWrapper(localName = "listarCursosInstitutoStringResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosInstitutoStringResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaString listarCursosInstitutoString(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "agregarDocenteEdicionCurso", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarDocenteEdicionCurso")
    @ResponseWrapper(localName = "agregarDocenteEdicionCursoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.AgregarDocenteEdicionCursoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String agregarDocenteEdicionCurso(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "inscribirEdicionCurso", targetNamespace = "http://server.edEXT/", className = "edEXT.server.InscribirEdicionCurso")
    @ResponseWrapper(localName = "inscribirEdicionCursoResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.InscribirEdicionCursoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String inscribirEdicionCurso(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebMethod
    @RequestWrapper(localName = "listarCursosCategoria", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosCategoria")
    @ResponseWrapper(localName = "listarCursosCategoriaResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarCursosCategoriaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaCursos listarCursosCategoria(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "listarDocentes", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarDocentes")
    @ResponseWrapper(localName = "listarDocentesResponse", targetNamespace = "http://server.edEXT/", className = "edEXT.server.ListarDocentesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edEXT.server.DtListaString listarDocentes()
;
}
