
package edEXT.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-21T01:20:02.885-03:00
 * Generated source version: 3.4.0
 *
 */
public final class Servidor_ServidorPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.edEXT/", "ServidorService");

    private Servidor_ServidorPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServidorService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ServidorService ss = new ServidorService(wsdlURL, SERVICE_NAME);
        Servidor port = ss.getServidorPort();

        {
        System.out.println("Invoking listarProgramasFormacionString...");
        edEXT.server.DtListaString _listarProgramasFormacionString__return = port.listarProgramasFormacionString();
        System.out.println("listarProgramasFormacionString.result=" + _listarProgramasFormacionString__return);


        }
        {
        System.out.println("Invoking altaInstituto...");
        java.lang.String _altaInstituto_arg0 = "_altaInstituto_arg0-768455366";
        java.lang.String _altaInstituto__return = port.altaInstituto(_altaInstituto_arg0);
        System.out.println("altaInstituto.result=" + _altaInstituto__return);


        }
        {
        System.out.println("Invoking incrementarVisitaCurso...");
        java.lang.String _incrementarVisitaCurso_arg0 = "_incrementarVisitaCurso_arg01384915441";
        java.lang.Integer _incrementarVisitaCurso__return = port.incrementarVisitaCurso(_incrementarVisitaCurso_arg0);
        System.out.println("incrementarVisitaCurso.result=" + _incrementarVisitaCurso__return);


        }
        {
        System.out.println("Invoking seleccionarUsuario...");
        java.lang.String _seleccionarUsuario_arg0 = "_seleccionarUsuario_arg0-437002684";
        edEXT.server.DtInfoUsuario _seleccionarUsuario__return = port.seleccionarUsuario(_seleccionarUsuario_arg0);
        System.out.println("seleccionarUsuario.result=" + _seleccionarUsuario__return);


        }
        {
        System.out.println("Invoking listarCursosCategoriaString...");
        java.lang.String _listarCursosCategoriaString_arg0 = "_listarCursosCategoriaString_arg0-1980491782";
        edEXT.server.DtListaString _listarCursosCategoriaString__return = port.listarCursosCategoriaString(_listarCursosCategoriaString_arg0);
        System.out.println("listarCursosCategoriaString.result=" + _listarCursosCategoriaString__return);


        }
        {
        System.out.println("Invoking puntuarCurso...");
        java.lang.String _puntuarCurso_arg0 = "_puntuarCurso_arg02004207229";
        java.lang.String _puntuarCurso_arg1 = "_puntuarCurso_arg1-1225652764";
        java.lang.Integer _puntuarCurso_arg2 = Integer.valueOf(1298186141);
        java.lang.String _puntuarCurso__return = port.puntuarCurso(_puntuarCurso_arg0, _puntuarCurso_arg1, _puntuarCurso_arg2);
        System.out.println("puntuarCurso.result=" + _puntuarCurso__return);


        }
        {
        System.out.println("Invoking getDtInfoCursoEdicion...");
        java.lang.String _getDtInfoCursoEdicion_arg0 = "_getDtInfoCursoEdicion_arg0-273638588";
        edEXT.server.DtCursoEdicion _getDtInfoCursoEdicion__return = port.getDtInfoCursoEdicion(_getDtInfoCursoEdicion_arg0);
        System.out.println("getDtInfoCursoEdicion.result=" + _getDtInfoCursoEdicion__return);


        }
        {
        System.out.println("Invoking agregarPreviaCurso...");
        java.lang.String _agregarPreviaCurso_arg0 = "_agregarPreviaCurso_arg0884872342";
        java.lang.String _agregarPreviaCurso_arg1 = "_agregarPreviaCurso_arg1-1859456158";
        java.lang.String _agregarPreviaCurso__return = port.agregarPreviaCurso(_agregarPreviaCurso_arg0, _agregarPreviaCurso_arg1);
        System.out.println("agregarPreviaCurso.result=" + _agregarPreviaCurso__return);


        }
        {
        System.out.println("Invoking listarCategorias...");
        edEXT.server.DtListaString _listarCategorias__return = port.listarCategorias();
        System.out.println("listarCategorias.result=" + _listarCategorias__return);


        }
        {
        System.out.println("Invoking listarUsuarios...");
        edEXT.server.DtListaUsuarios _listarUsuarios__return = port.listarUsuarios();
        System.out.println("listarUsuarios.result=" + _listarUsuarios__return);


        }
        {
        System.out.println("Invoking finalizarEdicion...");
        java.lang.String _finalizarEdicion_arg0 = "_finalizarEdicion_arg0-245865806";
        java.lang.String _finalizarEdicion__return = port.finalizarEdicion(_finalizarEdicion_arg0);
        System.out.println("finalizarEdicion.result=" + _finalizarEdicion__return);


        }
        {
        System.out.println("Invoking seleccionarUsuarioCorreo...");
        java.lang.String _seleccionarUsuarioCorreo_arg0 = "_seleccionarUsuarioCorreo_arg0466139502";
        edEXT.server.DtInfoUsuario _seleccionarUsuarioCorreo__return = port.seleccionarUsuarioCorreo(_seleccionarUsuarioCorreo_arg0);
        System.out.println("seleccionarUsuarioCorreo.result=" + _seleccionarUsuarioCorreo__return);


        }
        {
        System.out.println("Invoking altaEstudiante...");
        java.lang.String _altaEstudiante_arg0 = "_altaEstudiante_arg01163004879";
        java.lang.String _altaEstudiante_arg1 = "_altaEstudiante_arg1536816218";
        java.lang.String _altaEstudiante_arg2 = "_altaEstudiante_arg2-1811135018";
        java.lang.String _altaEstudiante_arg3 = "_altaEstudiante_arg3259617126";
        javax.xml.datatype.XMLGregorianCalendar _altaEstudiante_arg4 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.029-03:00");
        java.lang.String _altaEstudiante_arg5 = "_altaEstudiante_arg5195245021";
        java.lang.String _altaEstudiante_arg6 = "_altaEstudiante_arg6-1204815971";
        java.lang.String _altaEstudiante__return = port.altaEstudiante(_altaEstudiante_arg0, _altaEstudiante_arg1, _altaEstudiante_arg2, _altaEstudiante_arg3, _altaEstudiante_arg4, _altaEstudiante_arg5, _altaEstudiante_arg6);
        System.out.println("altaEstudiante.result=" + _altaEstudiante__return);


        }
        {
        System.out.println("Invoking listarEstudiantes...");
        edEXT.server.DtListaString _listarEstudiantes__return = port.listarEstudiantes();
        System.out.println("listarEstudiantes.result=" + _listarEstudiantes__return);


        }
        {
        System.out.println("Invoking listarCursos...");
        edEXT.server.DtListaCursos _listarCursos__return = port.listarCursos();
        System.out.println("listarCursos.result=" + _listarCursos__return);


        }
        {
        System.out.println("Invoking listarInstitutos...");
        edEXT.server.DtListaString _listarInstitutos__return = port.listarInstitutos();
        System.out.println("listarInstitutos.result=" + _listarInstitutos__return);


        }
        {
        System.out.println("Invoking aceptarInscripcionEdicion...");
        java.lang.String _aceptarInscripcionEdicion_arg0 = "_aceptarInscripcionEdicion_arg01196134302";
        java.lang.String _aceptarInscripcionEdicion_arg1 = "_aceptarInscripcionEdicion_arg1668920782";
        java.lang.String _aceptarInscripcionEdicion__return = port.aceptarInscripcionEdicion(_aceptarInscripcionEdicion_arg0, _aceptarInscripcionEdicion_arg1);
        System.out.println("aceptarInscripcionEdicion.result=" + _aceptarInscripcionEdicion__return);


        }
        {
        System.out.println("Invoking listarCursosInstituto...");
        java.lang.String _listarCursosInstituto_arg0 = "_listarCursosInstituto_arg01748479518";
        edEXT.server.DtListaCursos _listarCursosInstituto__return = port.listarCursosInstituto(_listarCursosInstituto_arg0);
        System.out.println("listarCursosInstituto.result=" + _listarCursosInstituto__return);


        }
        {
        System.out.println("Invoking crearEdicionCurso...");
        java.lang.String _crearEdicionCurso_arg0 = "_crearEdicionCurso_arg0698341329";
        java.lang.String _crearEdicionCurso_arg1 = "_crearEdicionCurso_arg11592862915";
        javax.xml.datatype.XMLGregorianCalendar _crearEdicionCurso_arg2 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.039-03:00");
        javax.xml.datatype.XMLGregorianCalendar _crearEdicionCurso_arg3 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.040-03:00");
        int _crearEdicionCurso_arg4 = -666347248;
        javax.xml.datatype.XMLGregorianCalendar _crearEdicionCurso_arg5 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.041-03:00");
        java.lang.String _crearEdicionCurso_arg6 = "_crearEdicionCurso_arg62069216290";
        java.util.List<java.lang.String> _crearEdicionCurso_arg7 = new java.util.ArrayList<java.lang.String>();
        java.lang.String _crearEdicionCurso_arg7Val1 = "_crearEdicionCurso_arg7Val-907717205";
        _crearEdicionCurso_arg7.add(_crearEdicionCurso_arg7Val1);
        java.lang.String _crearEdicionCurso__return = port.crearEdicionCurso(_crearEdicionCurso_arg0, _crearEdicionCurso_arg1, _crearEdicionCurso_arg2, _crearEdicionCurso_arg3, _crearEdicionCurso_arg4, _crearEdicionCurso_arg5, _crearEdicionCurso_arg6, _crearEdicionCurso_arg7);
        System.out.println("crearEdicionCurso.result=" + _crearEdicionCurso__return);


        }
        {
        System.out.println("Invoking seleccionarCurso...");
        java.lang.String _seleccionarCurso_arg0 = "_seleccionarCurso_arg0-721481652";
        edEXT.server.DtListaCursoEdiciones _seleccionarCurso__return = port.seleccionarCurso(_seleccionarCurso_arg0);
        System.out.println("seleccionarCurso.result=" + _seleccionarCurso__return);


        }
        {
        System.out.println("Invoking seleccionarProgramaFormacion...");
        java.lang.String _seleccionarProgramaFormacion_arg0 = "_seleccionarProgramaFormacion_arg0-1599923019";
        edEXT.server.DtProgramaFormacion _seleccionarProgramaFormacion__return = port.seleccionarProgramaFormacion(_seleccionarProgramaFormacion_arg0);
        System.out.println("seleccionarProgramaFormacion.result=" + _seleccionarProgramaFormacion__return);


        }
        {
        System.out.println("Invoking obtenerCertificadoProgramaFormacion...");
        java.lang.String _obtenerCertificadoProgramaFormacion_arg0 = "_obtenerCertificadoProgramaFormacion_arg0-1560106387";
        java.lang.String _obtenerCertificadoProgramaFormacion_arg1 = "_obtenerCertificadoProgramaFormacion_arg191297628";
        edEXT.server.DtCertificadoProgramaFormacion _obtenerCertificadoProgramaFormacion__return = port.obtenerCertificadoProgramaFormacion(_obtenerCertificadoProgramaFormacion_arg0, _obtenerCertificadoProgramaFormacion_arg1);
        System.out.println("obtenerCertificadoProgramaFormacion.result=" + _obtenerCertificadoProgramaFormacion__return);


        }
        {
        System.out.println("Invoking ingresarCurso...");
        java.lang.String _ingresarCurso_arg0 = "_ingresarCurso_arg01171803628";
        java.lang.String _ingresarCurso_arg1 = "_ingresarCurso_arg1-1373840905";
        java.lang.String _ingresarCurso_arg2 = "_ingresarCurso_arg21740579705";
        java.lang.String _ingresarCurso_arg3 = "_ingresarCurso_arg31577242443";
        int _ingresarCurso_arg4 = 1446848168;
        int _ingresarCurso_arg5 = -1644087916;
        java.lang.String _ingresarCurso_arg6 = "_ingresarCurso_arg6948383489";
        javax.xml.datatype.XMLGregorianCalendar _ingresarCurso_arg7 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.047-03:00");
        java.lang.String _ingresarCurso_arg8 = "_ingresarCurso_arg8-1062206459";
        java.util.List<java.lang.String> _ingresarCurso_arg9 = new java.util.ArrayList<java.lang.String>();
        java.lang.String _ingresarCurso_arg9Val1 = "_ingresarCurso_arg9Val1489205180";
        _ingresarCurso_arg9.add(_ingresarCurso_arg9Val1);
        java.util.List<java.lang.String> _ingresarCurso_arg10 = new java.util.ArrayList<java.lang.String>();
        java.lang.String _ingresarCurso_arg10Val1 = "_ingresarCurso_arg10Val-1781440284";
        _ingresarCurso_arg10.add(_ingresarCurso_arg10Val1);
        java.lang.String _ingresarCurso__return = port.ingresarCurso(_ingresarCurso_arg0, _ingresarCurso_arg1, _ingresarCurso_arg2, _ingresarCurso_arg3, _ingresarCurso_arg4, _ingresarCurso_arg5, _ingresarCurso_arg6, _ingresarCurso_arg7, _ingresarCurso_arg8, _ingresarCurso_arg9, _ingresarCurso_arg10);
        System.out.println("ingresarCurso.result=" + _ingresarCurso__return);


        }
        {
        System.out.println("Invoking agregarCursoEdicionComentario...");
        java.lang.String _agregarCursoEdicionComentario_arg0 = "_agregarCursoEdicionComentario_arg01648124284";
        java.lang.String _agregarCursoEdicionComentario_arg1 = "_agregarCursoEdicionComentario_arg1-1971657871";
        java.lang.String _agregarCursoEdicionComentario_arg2 = "_agregarCursoEdicionComentario_arg2-1883284545";
        java.lang.String _agregarCursoEdicionComentario__return = port.agregarCursoEdicionComentario(_agregarCursoEdicionComentario_arg0, _agregarCursoEdicionComentario_arg1, _agregarCursoEdicionComentario_arg2);
        System.out.println("agregarCursoEdicionComentario.result=" + _agregarCursoEdicionComentario__return);


        }
        {
        System.out.println("Invoking altaDocente...");
        java.lang.String _altaDocente_arg0 = "_altaDocente_arg0-857685459";
        java.lang.String _altaDocente_arg1 = "_altaDocente_arg11812266983";
        java.lang.String _altaDocente_arg2 = "_altaDocente_arg21202099528";
        java.lang.String _altaDocente_arg3 = "_altaDocente_arg319824133";
        javax.xml.datatype.XMLGregorianCalendar _altaDocente_arg4 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.052-03:00");
        java.lang.String _altaDocente_arg5 = "_altaDocente_arg5-861712842";
        java.lang.String _altaDocente_arg6 = "_altaDocente_arg6-913105977";
        java.lang.String _altaDocente_arg7 = "_altaDocente_arg7-891699005";
        java.lang.String _altaDocente__return = port.altaDocente(_altaDocente_arg0, _altaDocente_arg1, _altaDocente_arg2, _altaDocente_arg3, _altaDocente_arg4, _altaDocente_arg5, _altaDocente_arg6, _altaDocente_arg7);
        System.out.println("altaDocente.result=" + _altaDocente__return);


        }
        {
        System.out.println("Invoking seleccionarInstituto...");
        java.lang.String _seleccionarInstituto_arg0 = "_seleccionarInstituto_arg0-1367687100";
        edEXT.server.DtInfoInstituto _seleccionarInstituto__return = port.seleccionarInstituto(_seleccionarInstituto_arg0);
        System.out.println("seleccionarInstituto.result=" + _seleccionarInstituto__return);


        }
        {
        System.out.println("Invoking modificarDocente...");
        java.lang.String _modificarDocente_arg0 = "_modificarDocente_arg0-91265255";
        java.lang.String _modificarDocente_arg1 = "_modificarDocente_arg1-1041044626";
        java.lang.String _modificarDocente_arg2 = "_modificarDocente_arg2754399637";
        javax.xml.datatype.XMLGregorianCalendar _modificarDocente_arg3 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.057-03:00");
        java.lang.String _modificarDocente_arg4 = "_modificarDocente_arg4940512889";
        java.lang.String _modificarDocente_arg5 = "_modificarDocente_arg51782469725";
        java.lang.String _modificarDocente__return = port.modificarDocente(_modificarDocente_arg0, _modificarDocente_arg1, _modificarDocente_arg2, _modificarDocente_arg3, _modificarDocente_arg4, _modificarDocente_arg5);
        System.out.println("modificarDocente.result=" + _modificarDocente__return);


        }
        {
        System.out.println("Invoking agregarCursoProgramaFormacion...");
        java.lang.String _agregarCursoProgramaFormacion_arg0 = "_agregarCursoProgramaFormacion_arg0498066044";
        java.lang.String _agregarCursoProgramaFormacion_arg1 = "_agregarCursoProgramaFormacion_arg11486882843";
        java.lang.String _agregarCursoProgramaFormacion__return = port.agregarCursoProgramaFormacion(_agregarCursoProgramaFormacion_arg0, _agregarCursoProgramaFormacion_arg1);
        System.out.println("agregarCursoProgramaFormacion.result=" + _agregarCursoProgramaFormacion__return);


        }
        {
        System.out.println("Invoking modificarEstudiante...");
        java.lang.String _modificarEstudiante_arg0 = "_modificarEstudiante_arg0-1090274036";
        java.lang.String _modificarEstudiante_arg1 = "_modificarEstudiante_arg1-845961148";
        java.lang.String _modificarEstudiante_arg2 = "_modificarEstudiante_arg2236211880";
        javax.xml.datatype.XMLGregorianCalendar _modificarEstudiante_arg3 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.061-03:00");
        java.lang.String _modificarEstudiante_arg4 = "_modificarEstudiante_arg4600916177";
        java.lang.String _modificarEstudiante__return = port.modificarEstudiante(_modificarEstudiante_arg0, _modificarEstudiante_arg1, _modificarEstudiante_arg2, _modificarEstudiante_arg3, _modificarEstudiante_arg4);
        System.out.println("modificarEstudiante.result=" + _modificarEstudiante__return);


        }
        {
        System.out.println("Invoking agregarRespuestaCursoEdicionComentario...");
        long _agregarRespuestaCursoEdicionComentario_arg0 = -3182587866808768928l;
        java.lang.String _agregarRespuestaCursoEdicionComentario_arg1 = "_agregarRespuestaCursoEdicionComentario_arg1826244288";
        java.lang.String _agregarRespuestaCursoEdicionComentario_arg2 = "_agregarRespuestaCursoEdicionComentario_arg2-1975296248";
        java.lang.String _agregarRespuestaCursoEdicionComentario_arg3 = "_agregarRespuestaCursoEdicionComentario_arg3-1301580910";
        java.lang.String _agregarRespuestaCursoEdicionComentario__return = port.agregarRespuestaCursoEdicionComentario(_agregarRespuestaCursoEdicionComentario_arg0, _agregarRespuestaCursoEdicionComentario_arg1, _agregarRespuestaCursoEdicionComentario_arg2, _agregarRespuestaCursoEdicionComentario_arg3);
        System.out.println("agregarRespuestaCursoEdicionComentario.result=" + _agregarRespuestaCursoEdicionComentario__return);


        }
        {
        System.out.println("Invoking listarCursosEstudiante...");
        java.lang.String _listarCursosEstudiante_arg0 = "_listarCursosEstudiante_arg0-1298006164";
        edEXT.server.DtListaCursos _listarCursosEstudiante__return = port.listarCursosEstudiante(_listarCursosEstudiante_arg0);
        System.out.println("listarCursosEstudiante.result=" + _listarCursosEstudiante__return);


        }
        {
        System.out.println("Invoking listarDocentesInstituto...");
        java.lang.String _listarDocentesInstituto_arg0 = "_listarDocentesInstituto_arg01208658414";
        edEXT.server.DtListaString _listarDocentesInstituto__return = port.listarDocentesInstituto(_listarDocentesInstituto_arg0);
        System.out.println("listarDocentesInstituto.result=" + _listarDocentesInstituto__return);


        }
        {
        System.out.println("Invoking tramitarCertificadoProgramaFormacion...");
        java.lang.String _tramitarCertificadoProgramaFormacion_arg0 = "_tramitarCertificadoProgramaFormacion_arg0861411029";
        java.lang.String _tramitarCertificadoProgramaFormacion_arg1 = "_tramitarCertificadoProgramaFormacion_arg1401460522";
        java.lang.String _tramitarCertificadoProgramaFormacion__return = port.tramitarCertificadoProgramaFormacion(_tramitarCertificadoProgramaFormacion_arg0, _tramitarCertificadoProgramaFormacion_arg1);
        System.out.println("tramitarCertificadoProgramaFormacion.result=" + _tramitarCertificadoProgramaFormacion__return);


        }
        {
        System.out.println("Invoking seleccionarCategoria...");
        java.lang.String _seleccionarCategoria_arg0 = "_seleccionarCategoria_arg0345077336";
        edEXT.server.DtInfoCategoria _seleccionarCategoria__return = port.seleccionarCategoria(_seleccionarCategoria_arg0);
        System.out.println("seleccionarCategoria.result=" + _seleccionarCategoria__return);


        }
        {
        System.out.println("Invoking getDtInfoCursoEdicionVigente...");
        java.lang.String _getDtInfoCursoEdicionVigente_arg0 = "_getDtInfoCursoEdicionVigente_arg01400194364";
        edEXT.server.DtCursoEdicion _getDtInfoCursoEdicionVigente__return = port.getDtInfoCursoEdicionVigente(_getDtInfoCursoEdicionVigente_arg0);
        System.out.println("getDtInfoCursoEdicionVigente.result=" + _getDtInfoCursoEdicionVigente__return);


        }
        {
        System.out.println("Invoking altaCategoria...");
        java.lang.String _altaCategoria_arg0 = "_altaCategoria_arg0431936076";
        java.lang.String _altaCategoria__return = port.altaCategoria(_altaCategoria_arg0);
        System.out.println("altaCategoria.result=" + _altaCategoria__return);


        }
        {
        System.out.println("Invoking desitirInscripcionEdicion...");
        java.lang.String _desitirInscripcionEdicion_arg0 = "_desitirInscripcionEdicion_arg0-264720780";
        java.lang.String _desitirInscripcionEdicion_arg1 = "_desitirInscripcionEdicion_arg11638810277";
        java.lang.String _desitirInscripcionEdicion__return = port.desitirInscripcionEdicion(_desitirInscripcionEdicion_arg0, _desitirInscripcionEdicion_arg1);
        System.out.println("desitirInscripcionEdicion.result=" + _desitirInscripcionEdicion__return);


        }
        {
        System.out.println("Invoking getDtInfoCurso...");
        java.lang.String _getDtInfoCurso_arg0 = "_getDtInfoCurso_arg01406485849";
        edEXT.server.DtInfoCurso _getDtInfoCurso__return = port.getDtInfoCurso(_getDtInfoCurso_arg0);
        System.out.println("getDtInfoCurso.result=" + _getDtInfoCurso__return);


        }
        {
        System.out.println("Invoking inscribirProgramaFormacion...");
        java.lang.String _inscribirProgramaFormacion_arg0 = "_inscribirProgramaFormacion_arg01757892078";
        java.lang.String _inscribirProgramaFormacion_arg1 = "_inscribirProgramaFormacion_arg1-1651861308";
        javax.xml.datatype.XMLGregorianCalendar _inscribirProgramaFormacion_arg2 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.069-03:00");
        java.lang.String _inscribirProgramaFormacion__return = port.inscribirProgramaFormacion(_inscribirProgramaFormacion_arg0, _inscribirProgramaFormacion_arg1, _inscribirProgramaFormacion_arg2);
        System.out.println("inscribirProgramaFormacion.result=" + _inscribirProgramaFormacion__return);


        }
        {
        System.out.println("Invoking crearProgramaFormacion...");
        java.lang.String _crearProgramaFormacion_arg0 = "_crearProgramaFormacion_arg0-1322957837";
        java.lang.String _crearProgramaFormacion_arg1 = "_crearProgramaFormacion_arg1-997157219";
        javax.xml.datatype.XMLGregorianCalendar _crearProgramaFormacion_arg2 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.072-03:00");
        javax.xml.datatype.XMLGregorianCalendar _crearProgramaFormacion_arg3 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.073-03:00");
        java.lang.String _crearProgramaFormacion_arg4 = "_crearProgramaFormacion_arg4-1495463841";
        java.lang.String _crearProgramaFormacion__return = port.crearProgramaFormacion(_crearProgramaFormacion_arg0, _crearProgramaFormacion_arg1, _crearProgramaFormacion_arg2, _crearProgramaFormacion_arg3, _crearProgramaFormacion_arg4);
        System.out.println("crearProgramaFormacion.result=" + _crearProgramaFormacion__return);


        }
        {
        System.out.println("Invoking listarCursosVisitas...");
        edEXT.server.DtListaCursos _listarCursosVisitas__return = port.listarCursosVisitas();
        System.out.println("listarCursosVisitas.result=" + _listarCursosVisitas__return);


        }
        {
        System.out.println("Invoking rechazarInscripcionEdicion...");
        java.lang.String _rechazarInscripcionEdicion_arg0 = "_rechazarInscripcionEdicion_arg0123625971";
        java.lang.String _rechazarInscripcionEdicion_arg1 = "_rechazarInscripcionEdicion_arg1609442519";
        java.lang.String _rechazarInscripcionEdicion__return = port.rechazarInscripcionEdicion(_rechazarInscripcionEdicion_arg0, _rechazarInscripcionEdicion_arg1);
        System.out.println("rechazarInscripcionEdicion.result=" + _rechazarInscripcionEdicion__return);


        }
        {
        System.out.println("Invoking listarCursosString...");
        edEXT.server.DtListaString _listarCursosString__return = port.listarCursosString();
        System.out.println("listarCursosString.result=" + _listarCursosString__return);


        }
        {
        System.out.println("Invoking agregarCategoriaCurso...");
        java.lang.String _agregarCategoriaCurso_arg0 = "_agregarCategoriaCurso_arg01743840586";
        java.lang.String _agregarCategoriaCurso_arg1 = "_agregarCategoriaCurso_arg1891124059";
        java.lang.String _agregarCategoriaCurso__return = port.agregarCategoriaCurso(_agregarCategoriaCurso_arg0, _agregarCategoriaCurso_arg1);
        System.out.println("agregarCategoriaCurso.result=" + _agregarCategoriaCurso__return);


        }
        {
        System.out.println("Invoking calificarInscripcionEdicion...");
        java.lang.String _calificarInscripcionEdicion_arg0 = "_calificarInscripcionEdicion_arg0598725186";
        java.lang.String _calificarInscripcionEdicion_arg1 = "_calificarInscripcionEdicion_arg11158118130";
        java.lang.Integer _calificarInscripcionEdicion_arg2 = Integer.valueOf(-940357612);
        javax.xml.datatype.XMLGregorianCalendar _calificarInscripcionEdicion_arg3 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.077-03:00");
        java.lang.String _calificarInscripcionEdicion__return = port.calificarInscripcionEdicion(_calificarInscripcionEdicion_arg0, _calificarInscripcionEdicion_arg1, _calificarInscripcionEdicion_arg2, _calificarInscripcionEdicion_arg3);
        System.out.println("calificarInscripcionEdicion.result=" + _calificarInscripcionEdicion__return);


        }
        {
        System.out.println("Invoking listarCursosInstitutoString...");
        java.lang.String _listarCursosInstitutoString_arg0 = "_listarCursosInstitutoString_arg01688617963";
        edEXT.server.DtListaString _listarCursosInstitutoString__return = port.listarCursosInstitutoString(_listarCursosInstitutoString_arg0);
        System.out.println("listarCursosInstitutoString.result=" + _listarCursosInstitutoString__return);


        }
        {
        System.out.println("Invoking agregarDocenteEdicionCurso...");
        java.lang.String _agregarDocenteEdicionCurso_arg0 = "_agregarDocenteEdicionCurso_arg0-1437483913";
        java.lang.String _agregarDocenteEdicionCurso_arg1 = "_agregarDocenteEdicionCurso_arg1873155134";
        java.lang.String _agregarDocenteEdicionCurso__return = port.agregarDocenteEdicionCurso(_agregarDocenteEdicionCurso_arg0, _agregarDocenteEdicionCurso_arg1);
        System.out.println("agregarDocenteEdicionCurso.result=" + _agregarDocenteEdicionCurso__return);


        }
        {
        System.out.println("Invoking inscribirEdicionCurso...");
        java.lang.String _inscribirEdicionCurso_arg0 = "_inscribirEdicionCurso_arg02131332834";
        java.lang.String _inscribirEdicionCurso_arg1 = "_inscribirEdicionCurso_arg1-1302865965";
        javax.xml.datatype.XMLGregorianCalendar _inscribirEdicionCurso_arg2 = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2020-11-21T01:20:03.080-03:00");
        java.lang.String _inscribirEdicionCurso_arg3 = "_inscribirEdicionCurso_arg3-758451124";
        java.lang.String _inscribirEdicionCurso__return = port.inscribirEdicionCurso(_inscribirEdicionCurso_arg0, _inscribirEdicionCurso_arg1, _inscribirEdicionCurso_arg2, _inscribirEdicionCurso_arg3);
        System.out.println("inscribirEdicionCurso.result=" + _inscribirEdicionCurso__return);


        }
        {
        System.out.println("Invoking listarCursosCategoria...");
        java.lang.String _listarCursosCategoria_arg0 = "_listarCursosCategoria_arg0-507125333";
        edEXT.server.DtListaCursos _listarCursosCategoria__return = port.listarCursosCategoria(_listarCursosCategoria_arg0);
        System.out.println("listarCursosCategoria.result=" + _listarCursosCategoria__return);


        }
        {
        System.out.println("Invoking listarDocentes...");
        edEXT.server.DtListaString _listarDocentes__return = port.listarDocentes();
        System.out.println("listarDocentes.result=" + _listarDocentes__return);


        }

        System.exit(0);
    }

}
